/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hoodie.glb 
Author: yogaminggames (https://sketchfab.com/yogaminggames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-Hoodies/hoodie-2c674228f1e946b5b8f508f8f818e130
Title: Hoodie
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Hoodie(props) {
  const { nodes, materials } = useGLTF('/models/hoodie.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group scale={10}>
          <mesh geometry={nodes.Hoodie_FABRIC_3_FRONT_1850_0.geometry} material={materials.FABRIC_3_FRONT_1850} />
          <mesh geometry={nodes.Hoodie_FABRIC_3_FRONT_1850_0_1.geometry} material={materials.FABRIC_3_FRONT_1850} />
          <mesh geometry={nodes.Hoodie_FABRIC_3_FRONT_1850_0_2.geometry} material={materials.FABRIC_3_FRONT_1850} />
          <mesh geometry={nodes.Hoodie_FABRIC_3_FRONT_1850_0_3.geometry} material={materials.FABRIC_3_FRONT_1850} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/hoodie.glb')
